name: Build patcher

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libzip-dev

      - name: Build patcher
        run: |
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
