name: Build patcher

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install gcc-15
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:puni070/gcc-noble -y
          sudo apt update
          sudo apt-get install -y gcc-15 g++-15
          
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-15 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-15 100

      - name: Build patcher
        run: |
          mkdir build && cd build
          cmake ..
          make -j$(nproc)
